server.port=${PORT:8080}

whatsapp.verify.token=${WHATSAPP_VERIFY_TOKEN:chatBotWhatsAppVerifyToken}
whatsapp.access.token=${WHATSAPP_ACCESS_TOKEN}
whatsapp.phone.number.id=${WHATSAPP_PHONE_NUMBER_ID:1252189351304796}
whatsapp.business.account.id=${WHATSAPP_BUSINESS_ACCOUNT_ID:1573746260873765}

logging.level.com.example.whatsappbot=DEBUG
